### ISSUE TITLE
[Help Wanted]: GTK candidate highlight color can't be overwritten

### ISSUE THREAD

**Issue by HollowMan6** [openSUSE/IBus-Theme-Tools#2]
It looks like the GTK candidate highlight color can't be set in current version (v4.1.0), and I can't find a way to solve this issue.

It seems to be related to https://github.com/ibus/ibus/commit/bdc83bcbe3c9f07a267499c297db12c68af82fa2 , and the color can't be overwritten once the imported stylesheet has that color definitions. Maybe it's because that commit gets the color directly from the global GTK style properties, having no idea how to make a workaround except for changing the upstream.

I've tried adding the following seperately in the hope to change the GTK candidate highlight color in the tools' generated GTK stylesheets so far, and none of them successfully changed the candidate highlight color, but just follow the imported (base) GTK definitions.

1. 
```css
#IBusCandidate * {
  background-color: #000000;
  -gtk-secondary-caret-color: #000000;
}
```

2. 
```css
* {
  background-color: #000000;
  -gtk-secondary-caret-color: #000000;
}
```

If you know what's going on here, please tell me or simply submit a PR, thanks!
